theme: jekyll-theme-cayman
show_downloads: true
title: Constructing Indexes With R
description: Aggregating Complex Mathematical Formulas Into Reproducible R Code
site_url: https://tmbuza.github.io/indexbook/
