theme: jekyll-theme-cayman
show_downloads: true
title: Constructing Empowerment Indexes Using R
description: Aggregating Complex Index Formulas Into Reproducible R Code
site_url: https://tmbuza.github.io/indexbook/
